---
title: "gapminder-dplyr"
author: "Jamie Afflerbach"
date: "6/19/2019"
output: html_document
---

Loading tidyverse
```{r}
library(tidyverse)
```

Load data
```{r}
#loading the gapminder dataset from github

gapminder <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv")
```

```{r}
head(gapminder)
tail(gapminder)

#str() - stands for structure
str(gapminder)

#column names of gapminder
names(gapminder)
ncol(gapminder)
```

Look at individual dataframe variables
```{r}
#show me the lifeExp column
gapminder$lifeExp
gapminder$continent
```

Learning the `filter()` function
```{r}
filter(gapminder, lifeExp < 35)

#just look at mexico
filter(gapminder, country == "Mexico", year == 2002)
```

Average life expectency in Brazil between 1987 and 2007
```{r}
brazil_life_exp <- filter(gapminder, country == "Brazil", 
                          year > 1986,
                          year < 2008)
brazil_life_exp
mean(brazil_life_exp$lifeExp)
```







